config/routes.rb
Rails.application.routes.draw do
  get 'contact/index'
  get 'team/index'
  get 'static_pages/index'
  get 'static_pages/secret'
  get 'welcome/index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'welcome#index'
  resources :contact, only: [:index]
  resources :team, only: [:index]

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/attendance.rb
class Attendance < ApplicationRecord

  belongs_to :event
  belongs_to :user


end

app/models/event.rb
class Event < ApplicationRecord
  validates :start_date, presence: true
  validates :duration, presence: true, :numericality => { :greater_than_or_equal_to => 0 }
  validate :divisible_by_five
  validates :title, presence: true, length: { in: 5..140 }
  validates :description, presence: true, length: { in: 20..1000}
  validates :price, presence: true
  validates_inclusion_of :price, :in => 1..1000
  validates :location, presence: true

  has_many :users, through: :attendances
  has_many :attendances


  def divisible_by_five
    if (self.duration % 5) != 0
        self.errors[:base] << "Number must be divisible by 5!"
    end
  end

end

app/models/user.rb
class User < ApplicationRecord

  has_many :attendances
  has_many :events, foreign_key: 'admin_id', class_name: "Event"


end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/contact_controller.rb
class ContactController < ApplicationController
  def index
  end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
before_action :authenticate_user!, only: [:secret]
  def index
  end

  def secret
  end
end

app/controllers/team_controller.rb
class TeamController < ApplicationController
  def index
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/contact_helper.rb
module ContactHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/helpers/team_helper.rb
module TeamHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/contact/index.html.erb
<div class="card text-center mb-3">
  <div class="card-body">
    <h5 class="card-title font-weight-bold">Please don't contact us!</h5>
    <div class="card-text">
    <p>Our hotline in a poor country with slaved employees</p>
		<ul>
      <li>0800 555 554 the monday and friday btw 10h-12h</li><br><br>
      <li>Our hotline in a poor country with slaved employees</li>
      <li>Our hotline for premium customers</li>
      <li>06 28 29 55 88  24/7</li>
      <li>Be responsible, get premium !</li><br><br><br><br><br>


		</ul>
</div>
  </div>
</div>

app/views/layouts/application.htm.erb
<!DOCTYPE html>
<html>
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">

      <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
      <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
      <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>


    <title>TGP</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <header>
<nav class="navbar navbar-expand-lg navbar-light text-light bg-dark">
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarTogglerDemo01" aria-controls="navbarTogglerDemo01" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <div class="collapse navbar-collapse" id="navbarTogglerDemo01">
    <a class="navbar-brand text-white" <%= link_to "The Gossip Project", welcome_index_path%></a>
    <ul class="navbar-nav mr-auto mt-2 mt-lg-0">
      <li class="nav-item">
        <a class="nav-link text-light" <%= link_to "Team", team_index_path%></a>
      </li>
      <li class="nav-item">
        <a class="nav-link text-light" <%= link_to "Contact", contact_index_path%></a>
      </li>
      <%if logged_in? %>
      <li class="nav-item">
        <a class="nav-link text-light" <%= link_to "Participe, et créé un event", new_event_path%></a>
      </li>
      <%end%>
    </ul>
  </div>


  <%if logged_in? %>
  <div class="dropdown mr-5">
    <button class="btn btn-success dropdown-toggle" type="button" id="dropdownMenuButton" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
      <%=current_user.first_name%>
    </button>
    <div class="dropdown-menu" aria-labelledby="dropdownMenuButton">
      <a class="dropdown-item badge badge-pill badge-info" <%= link_to "Profil", author_path(current_user.id)%></a>
      <a class="dropdown-item badge badge-pill badge-danger" <%= link_to "Déconnection", session_path(session.id), method: :delete %>
      </div>
    </div>

    <%else%>
    <div class="dropdown mr-5">
      <button class="btn btn-danger dropdown-toggle " type="button" id="dropdownMenuButton" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
        Inscription / Connection
      </button>
      <div class="dropdown-menu" aria-labelledby="dropdownMenuButton">
        <a class="dropdown-item badge badge-pill badge-primary" <%= link_to "S'inscrire", new_author_path%></a>
        <a class="dropdown-item badge badge-pill badge-success" <%= link_to "Se connecter", new_author_path%></a>
      </div>
    </div>
    <%end%>

</nav>
  </header>
  <body>

    <%= yield %>
  </body>
</html>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">

      <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
      <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
      <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>


    <title>TGP</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <header>
<nav class="navbar navbar-expand-lg navbar-light text-light bg-dark">
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarTogglerDemo01" aria-controls="navbarTogglerDemo01" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <div class="collapse navbar-collapse" id="navbarTogglerDemo01">
    <a class="navbar-brand text-white" <%= link_to "Vannes Events", welcome_index_path%></a>
    <ul class="navbar-nav mr-auto mt-2 mt-lg-0">
      <li class="nav-item">
        <a class="nav-link text-light" <%= link_to "Team", team_index_path%></a>
      </li>
      <li class="nav-item">
        <a class="nav-link text-light" <%= link_to "Contact", contact_index_path%></a>
      </li>

    </ul>
  </div>

  <div class="dropdown mr-5">
      <button class="btn btn-danger dropdown-toggle " type="button" id="dropdownMenuButton" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
        Inscription / Connection
      </button>
      <div class="dropdown-menu" aria-labelledby="dropdownMenuButton">
        <a class="dropdown-item badge badge-pill badge-primary" <%= link_to "sign up", welcome_index_path%></a>
        <a class="dropdown-item badge badge-pill badge-success" <%= link_to "loggin", welcome_index_path%></a>
        <a class="dropdown-item badge badge-pill badge-success" <%= link_to "my profil", welcome_index_path%></a>
        <a class="dropdown-item badge badge-pill badge-success" <%= link_to "loggout", welcome_index_path%></a>
      </div>
    </div>


</nav>
  </header>
  <body>

    <%= yield %>
  </body>
</html>

app/views/static_pages/index.html.erb
<h1>StaticPages#index</h1>
<p>Find me in app/views/static_pages/index.html.erb</p>
<ul>
  <% if user_signed_in? %>
    <li>
      <%= link_to "Sign out", destroy_user_session_path, method: :delete %>
    </li>

    <li>
      Voici ton email : <%= current_user.email %>
    </li>

    <li>
      <%= link_to "Secret page", static_pages_secret_path %>
    </li>

    <li>
      <%= link_to "Edit email / password", edit_user_registration_path %>
    </li>

  <% else %>
    <li>
      <%= link_to "Sign in", new_user_session_path %>
    </li>

    <li>
      <%= link_to "Sign up", new_user_registration_path %>
    </li>

  <% end %>
</ul>

app/views/static_pages/secret.html.erb
<h1>StaticPages#secret</h1>
<p>Find me in app/views/static_pages/secret.html.erb</p>

app/views/team/index.html.erb
<div class="card text-center mb-3">
  <div class="card-body">
    <h5 class="card-title font-weight-bold">The best THP team ever seen</h5>
    <div class="card-text text-left">
    <p>Nothing would have been possible without them :</p>
		<ul>
			<li>Ray</li>
      <li>Raymond</li>
      <li>Robert</li>
      <li>Gislaine</li>

		</ul>
</div>
  </div>
</div>

app/views/welcome/index.html.erb
<div class="card text-center mb-3">
  <div class="card-body">
    <h5 class="card-title font-weight-bold">BIENVENUE <%=params[:id]%> !</h5>
    <p class="card-text">Ici c'est notre super site d'événements vannetais, il est chouette, non ?</p>
    <a class="btn btn-dark" <%= link_to "Soumettre un Event", welcome_index_path%></a>
  </div>
</div>